name: mcc2 build

on:
  push:
    paths:
      - '.github/workflows/mcc2.yml'
      - 'src/*'
      - 'test/*'
      - 'Makefile'

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - run: make test
