name: mcc2 build

on:
  push:
    paths:
      - '.github/workflows/mcc2.yml'
      - 'src/*'
      - 'test/*'
      - 'lib/*'
      - 'lib/bin/*'
      - 'Makefile'

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - run: make test
      - run: make self1t
      - run: make self2t
      - run: make self3t
