name: mcc2 build

on:
  push:
    paths:
      - '.github/workflows/mcc2.yml'
      - 'src/*'
      - 'test.sh'
      - 'Makefile'
      - 'tmp'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: build
        run: make test
      
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-without-markdown
          path: |
            tmp
              